version: '3.9'
services:
  #PHP Service
  php74-fpm:
    image: shgoudarzi/php-fpm-alpine-extended:latest    # ( replace with with your own version want )
    container_name: php-fpm
    restart: unless-stopped
    tty: true
#    ports:
#      - "9000:9000"
    volumes:
      #sites - working dir ( both side must be the same as root path of webserver conf like Nginx )
      - /home/web:/usr/share/nginx/html
      #Conf files
#      - /local/path/to/php.ini:/usr/local/etc/php/php.ini
#      - /local/path/to/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - TZ="Asia/Tehran"
